---
platform: linux
inputs:
- name: git-repo
- name: redis
- name: spring-boot-ci-image
outputs:
- name: distribution-repository
caches:
- path: maven
- path: gradle
run:
  path: sh
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      ${PWD}/git-repo/ci/scripts/build-project.sh

