version: "2"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
    - "6379:6379"
  build-project:
    image: springci/spring-boot-ci-image:master
    container_name: build-project
    volumes:
    - ../../../git-repo/:/git-repo
    - ../../../distribution-repository/:/distribution-repository
    depends_on:
      - redis
    command: /git-repo/ci/scripts/build-project.sh