resource_types:
  - name: java-cache-resource
    type: docker-image
    source: {repository: springio/java-cache-resource, tag: latest}
resources:
  - name: git-repo
    type: git
    source: &repo-source
      uri: https://github.com/mbhave/spring-boot.git
      branch: maven-restruct
  - name: maven-repo-cache
    type: java-cache-resource
    source:
      <<: *repo-source
      paths:
        - "**pom.xml"
      depth: 1
      commands:
        - "ls -la && ./mvnw -Dfast -DskipTests install dependency:go-offline"
      folders:
        - source: ~/.m2
          destination: m2
      cleanup:
        - "org.springframework.boot"
        - ".*SNAPSHOT"

jobs:
  - name: build
    plan:
      - get: git-repo
        trigger: true
      - get: maven-repo-cache
      - task: run-build
        file: git-repo/ci/tasks/run-build.yml
      - aggregate:
          - task: samples
            file: git-repo/ci/tasks/samples.yml
          - task: integration-tests
            file: git-repo/ci/tasks/integration-tests.yml
#  - name: samples
#    plan:
#      - get: git-repo
#        passed: [build]
#        trigger: true
#      - get: maven-repo-cache
#        passed: [build]
#      - task: samples
#        file: git-repo/ci/tasks/samples.yml
#  - name: integration-tests
#    plan:
#      - get: git-repo
#        passed: [build]
#        trigger: true
#      - get: maven-repo-cache
#        passed: [build]
#      - task: integration-tests
#        file: git-repo/ci/tasks/integration-tests.yml

